language: node_js
sudo: required
node_js:
  - '8'
dist: trusty
addons:
  chrome: stable
  apt:
    packages:
      # This is required to run new chrome on old trusty
      - libnss3
install: true
branches:
  only:
    - master
    - /^version_\d+\.x$/
cache:
  yarn: true
jobs:
  include:
    - script:
      - git config --global user.name "${GH_NAME}"
      - git config --global user.email "${GH_EMAIL}"
      - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages
      name: "website"
    - script: npm run test:integration
      before_script: 
        # Puppeteer setup
        - "sysctl kernel.unprivileged_userns_clone=1"
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        # Install
        - npm install
      name: "test:integration"
    - script: npm run test:unit
      before_script: npm install
      name: "test:unit"
    - script: npm run test:app-flow
      before_script: npm install
      name: "test:app-flow"
    - script: npm run lint
      before_script: npm install
      name: "lint"
